--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/tim03we/MyPlot
projects:
  MyPlot:
    icon: "icon.png"
    path: ""
    libs:
      - src: Falkirks/spoondetector/spoondetector
        version: ^0.0.0
...